import type { Metadata } from "next";
import { EB_Garamond, Inter, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-heading",
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-body",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-accent",
});

export const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Therapy Clinics Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${openSans.variable} ${poppins.variable} ${ebGaramond.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
